# Generated by Django 2.2.5 on 2020-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.IntegerField(blank=True, default=0, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.IntegerField(blank=True, default=0.0, null=True)),
                ('instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('uploads', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
                ('main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VueOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.CharField(blank=True, max_length=200, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('Level', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('fin_earl', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default=200, max_length=200, null=True)),
                ('Topic', models.CharField(blank=True, max_length=500, null=True)),
                ('sources', models.IntegerField(default=0)),
                ('style', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('files', models.ManyToManyField(to='Home.UploadFiles')),
            ],
        ),
    ]
