# Generated by Django 2.2.5 on 2020-08-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200731_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.CharField(blank=True, max_length=200, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('Level', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('fin_earl', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default=200, max_length=200, null=True)),
                ('Topic', models.CharField(blank=True, max_length=500, null=True)),
                ('sources', models.IntegerField(default=0)),
                ('style', models.IntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
                ('Order', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.VueOrders')),
            ],
        ),
    ]
