# Generated by Django 2.2.5 on 2020-08-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200805_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='Order',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vueorders',
            name='files',
            field=models.ManyToManyField(to='Home.UploadFiles'),
        ),
    ]
