# Generated by Django 2.2.5 on 2020-10-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livechat.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.ManyToManyField(blank=True, to='livechat.Message'),
        ),
    ]
