# Generated by Django 2.2.5 on 2020-10-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livechat', '0003_auto_20201018_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
    ]
